name: youtube_shorts
description: A vertical youtube shorts player. Show youtube shorts videos by a list of urls or the target channel name.
version: 1.1.0
homepage: https://pub.dev/packages/youtube_shorts
repository: https://github.com/igormidev/youtube_shorts
issue_tracker: https://github.com/igormidev/youtube_shorts/issues 

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  dart_debouncer: ^1.0.0
  synchronized: ^3.1.0
  easy_isolate_mixin: ^1.0.1
  enchanted_collection: ^1.2.0

  collection: ^1.18.0
  freezed_annotation: ^2.2.0
  html: ^0.15.0
  http: ^1.0.0
  http_parser: ^4.0.0
  json_annotation: ^4.5.0
  meta: ^1.7.0
  xml: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 

screenshots:
  - description: A visual demonstration of the cursor.
    path: art/screen_shot_1.PNG
  
topics:
  - layout
  - ui
  - youtube
  - webscrapping
  - video
  
false_secrets:
  - "lib/youtube_explode_fork/src/reverse_engineering/youtube_http_client.dart"
  - "lib/youtube_explode_fork/src/reverse_engineering/youtube_http_client.dart"
  - "lib/youtube_explode_fork/src/videos/video_controller.dart"
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
